Remove requirement for C++ preprocessor so that Asterisk Compiles on Limey Linux

diff --git a/asterisk/configure b/asterisk/configure
--- a/asterisk/configure
+++ b/asterisk/configure
@@ -6000,15 +6000,15 @@ rm -f conftest.err conftest.$ac_ext
 done
 # Because of `break', _AC_PREPROC_IFELSE's cleaning code was skipped.
 rm -f conftest.err conftest.$ac_ext
-if $ac_preproc_ok; then
-  :
-else
-  { { echo "$as_me:$LINENO: error: C++ preprocessor \"$CXXCPP\" fails sanity check
-See \`config.log' for more details." >&5
-echo "$as_me: error: C++ preprocessor \"$CXXCPP\" fails sanity check
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-fi
+#if $ac_preproc_ok; then
+#  :
+#else
+#  { { echo "$as_me:$LINENO: error: C++ preprocessor \"$CXXCPP\" fails sanity check
+#See \`config.log' for more details." >&5
+#echo "$as_me: error: C++ preprocessor \"$CXXCPP\" fails sanity check
+#See \`config.log' for more details." >&2;}
+#   { (exit 1); exit 1; }; }
+#fi
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
